services:
  backend:
    build:
      context: .
    image: tradingbot.azurecr.io/backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s

  ui:
    build:
      context: ./frontend
    image: tradingbot.azurecr.io/ui:latest
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://backend:8000
