PINECONE: 
  INDEX_NAME: trading-bot

SPLITTER: 
  CHUNK_SIZE: 1000
  CHUNK_OVERLAP_SIZE: 200

MODELS: 
  EMBEDDINGS:
    GOOGLE: "models/text-embedding-004"
    HUGGINGFACE: "BAAI/bge-small-en"
  REASONERS:
    GEMINI_FLASH: "gemini-2.0-flash"
    DEEPSEEK_R1: "deepseek-r1-distill-llama-70b"

TOOLS:
  RETRIEVER:
    TOP_K: 3
    SCORE_THRESHOLD: 0.5
  TAVILY:
    MAX_RESULTS: 5
