PINECONE: 
  INDEX_NAME: trading-bot

SPLITTER: 
  CHUNK_SIZE: 1000
  CHUNK_OVERLAP_SIZE: 200

MODELS: 
  EMBEDDINGS:
    GOOGLE: "models/text-embedding-004"
    HUGGINGFACE: "BAAI/bge-small-en"
  REASONERS:
    GEMINI_PRO: "gemini-2.5-pro-exp-03-25"
    DEEPSEEK_R1: "deepseek-r1-distill-llama-70b"
    
