from dataclasses import dataclass 
from trading_bot.utils import load_yaml 


CONFIG=load_yaml("config/config.yaml")

@dataclass 
class DataIngestionConstants:
    PINECONE_INDEX_NAME=CONFIG.PINECONE.INDEX_NAME
    SPLITTER_CHUNK_SIZE=CONFIG.SPLITTER.CHUNK_SIZE
    SPLITTER_CHUNK_OVERLAP_SIZE=CONFIG.SPLITTER.CHUNK_OVERLAP_SIZE
    GOOGLE_EMBEDDING_MODEL_NAME=CONFIG.MODELS.EMBEDDINGS.GOOGLE
    HUGGINGFACE_EMBEDDING_MODEL_NAME=CONFIG.MODELS.EMBEDDINGS.HUGGINGFACE


